jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
            Acme\UserBundle\Entity\User:
                algorithm:        sha1
                encode_as_base64: true
                iterations:       1


    role_hierarchy:
        ROLE_WORKER:      ROLE_USER
        ROLE_MANAGE:      ROLE_USER
        ROLE_ADMIN:       ROLE_MANAGE
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
           administrators:
               entity: { class: AcmeUserBundle:User }


    firewalls:

    #  main:
    #  pattern:    ^/resetPassword
    #  anonymous:  ~
    #  satic_content:
    #  pattern:  ^/static/imprint
    #  anonymous: ~


      login_firewall:
        pattern:    ^/login$
        anonymous:  ~

      secured_area:
        pattern:    ^/
        form_login:
          check_path: /login_check
          login_path: /login
          always_use_default_target_path: true
          default_target_path: /

        logout:
          path:   /logout
          target: /

    access_control:
          - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/, roles: ROLE_USER }


       # - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
      #  - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
