user:
    pattern:  /manage
    defaults: { _controller: "AcmeUserBundle:User:index" }

user_show:
    pattern:  /manage/{id}/show
    defaults: { _controller: "AcmeUserBundle:User:show" }

user_new:
    pattern:  /manage/new
    defaults: { _controller: "AcmeUserBundle:User:new" }

user_create:
    pattern:  /manage/create
    defaults: { _controller: "AcmeUserBundle:User:create" }
    requirements: { _method: post }

user_edit:
    pattern:  /manage/{id}/edit
    defaults: { _controller: "AcmeUserBundle:User:edit" }

user_update:
    pattern:  /manage/{id}/update
    defaults: { _controller: "AcmeUserBundle:User:update" }
    requirements: { _method: post }

user_activate:
    pattern:  /manage/{id}/activate
    defaults: { _controller: "AcmeUserBundle:User:activate" }
    requirements: { _method: post }

user_delete:
    pattern:  /manage/{id}/delete
    defaults: { _controller: "AcmeUserBundle:User:delete" }
    requirements: { _method: post }

user_myprofile:
    pattern:  /myprofile/{id}/
    defaults: { _controller: "AcmeUserBundle:User:show" }

user_updateprofile:
    pattern:  /myprofile/{id}/update
    defaults: { _controller: "AcmeUserBundle:User:updateProfile" }