parameters:
#    acme_user.example.class: Acme\UserBundle\Example

services:
#    acme_user.example:
#       class: Acme\UserBundle\UserListener
#       tags:
#            - { name: kernel.event_listener, event: security.interactive_login, method: setLocaleForAuthenticatedUser }
